name: flutter_schema_parse
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build: ^1.2.2
  recase: ^3.0.0
  dart_style: ^1.3.3
  inflection2: ^0.4.3
  json_schema: ^2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/sample_schema.json
